# Generated by Django 4.2.7 on 2023-11-03 11:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_remove_professor_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='offered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='university.professor'),
        ),
        migrations.AlterField(
            model_name='course',
            name='unit_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='department',
            name='head_of_department',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head_of', to='university.professor'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='university.course'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='university.student'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professors', to='university.department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollment_year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1300), django.core.validators.MaxValueValidator(1500)]),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course', 'semester')},
        ),
    ]
